// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2MfIYaDKiDTgfgsOqTMC8sOxUmD0pP-w',
    appId: '1:913389803660:web:49ac958c25c1693e2203a9',
    messagingSenderId: '913389803660',
    projectId: 'mealapp-5ab2c',
    authDomain: 'mealapp-5ab2c.firebaseapp.com',
    storageBucket: 'mealapp-5ab2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2S01miS2CRYt_li-w96thfIiAkmqIDqE',
    appId: '1:913389803660:android:fa51acc4e6fa3c422203a9',
    messagingSenderId: '913389803660',
    projectId: 'mealapp-5ab2c',
    storageBucket: 'mealapp-5ab2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAtPUvdnPPN2kLtKk_KLvKVxLp-Of2RRo',
    appId: '1:913389803660:ios:17827d74d8b4ecfd2203a9',
    messagingSenderId: '913389803660',
    projectId: 'mealapp-5ab2c',
    storageBucket: 'mealapp-5ab2c.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAtPUvdnPPN2kLtKk_KLvKVxLp-Of2RRo',
    appId: '1:913389803660:ios:17827d74d8b4ecfd2203a9',
    messagingSenderId: '913389803660',
    projectId: 'mealapp-5ab2c',
    storageBucket: 'mealapp-5ab2c.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2MfIYaDKiDTgfgsOqTMC8sOxUmD0pP-w',
    appId: '1:913389803660:web:f5d5864cc0c916f62203a9',
    messagingSenderId: '913389803660',
    projectId: 'mealapp-5ab2c',
    authDomain: 'mealapp-5ab2c.firebaseapp.com',
    storageBucket: 'mealapp-5ab2c.firebasestorage.app',
  );

}